version: '3.8'
services:
  postgres:
    container_name: "users_db"
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=users_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '6432:5432'
