spring:
  application:
    name: ssg
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:6432/users_db
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    user: document_user
    password: secret
    change-log: classpath:db/changelog/db-init.yaml

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %logger{36} %M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %M - %msg%n"
  file:
    name: log.txt
  level.root: info


